version: '3.7'

services:
  kurkkumopo-training:
    build: ../../ml-kurkkumopo-training
    image: kurkkumopo-training
    container_name: kurkkumopo-training
    volumes:
      - model:/src/model
      - imgs:/src/imgs
      - data:/src/data

  kurkkumopo-backend:
    build: ../../ml-kurkkumopo-backend
    image: kurkkumopo-backend
    container_name: kurkkumopo-backend
    volumes:
      - model:/src/model
    ports:
      - 5000:5000
    depends_on:
      - kurkkumopo-training

  kurkkumopo-frontend:
    build: ../../ml-kurkkumopo-frontend
    image: kurkkumopo-frontend
    container_name: kurkkumopo-frontend
    ports:
      - 3000:3000
    depends_on:
      - kurkkumopo-training
      - kurkkumopo-backend

volumes:
  model:
  imgs:
  data: